name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Main Stats (Includes Private)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=meswaramuthu&show_icons=true&theme=default&hide_border=true&include_all_commits=true&count_private=true
          path: image/github-stats.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=meswaramuthu&layout=compact&theme=default&hide_border=true
          path: image/top-langs.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          github_user: meswaramuthu
          step_commit_token: ${{ secrets.GH_PAT }}
          output: image/streak-stats.svg
          theme: default
          hide_border: true

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github stats automatically"
          file_pattern: "image/*.svg"
